# Criando DataFrames com base nos Datasets

In [1]:
import pandas as pd

# carregando DF de clientes (customers)

In [2]:
df_customers = pd.read_csv('./datasets/churn_customers.csv')

In [ ]:
### Mostrando as 5 primeiras linhas da tabela
df_customers.head()

   customerID  gender  SeniorCitizen Partner Dependents
0  7590-VHVEG  Female              0     Yes         No
1  5575-GNVDE    Male              0      No         No
2  3668-QPYBK    Male              0      No         No
3  7795-CFOCW    Male              0      No         No
4  9237-HQITU  Female              0      No         No

In [ ]:
### Adquirindo informações sobre quantidade de dados, tipos de dados e outras informações da tabela.
df_customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customerID     7043 non-null   str
 1   gender         7043 non-null   str
 2   SeniorCitizen  7043 non-null   int64
 3   Partner        7043 non-null   str
 4   Dependents     7043 non-null   str
dtypes: int64(1), str(4)
memory usage: 275.2 KB

# Puxando as demais tabelas

In [ ]:
### Importando os arquivos CSV's de "Services" e "Contracts"

df_services = pd.read_csv('./datasets/churn_services.csv')
df_contracts = pd.read_csv('./datasets/churn_contracts.csv')

In [ ]:
### Analisando as colunas de services de forma tabular
df_services.head()

,customerID,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
0,7590-VHVEG,No,No phone service,DSL,No,Yes,No,No,No,No
1,5575-GNVDE,Yes,No,DSL,Yes,No,Yes,No,No,No
2,3668-QPYBK,Yes,No,DSL,Yes,Yes,No,No,No,No
3,7795-CFOCW,No,No phone service,DSL,Yes,No,Yes,Yes,No,No
4,9237-HQITU,Yes,No,Fiber optic,No,No,No,No,No,No

In [12]:
### Analisando as informações contidas na tabela services
df_services.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   PhoneService      7043 non-null   str
 2   MultipleLines     7043 non-null   str
 3   InternetService   7043 non-null   str
 4   OnlineSecurity    7043 non-null   str
 5   OnlineBackup      7043 non-null   str
 6   DeviceProtection  7043 non-null   str
 7   TechSupport       7043 non-null   str
 8   StreamingTV       7043 non-null   str
 9   StreamingMovies   7043 non-null   str
dtypes: str(10)
memory usage: 550.4 KB

In [13]:
### Analisando as colunas de contracts de forma tabular
df_contracts.head()

,customerID,tenure,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,1,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,34,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,2,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,45,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,2,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [14]:
### Analisando as informações de Contracts

df_contracts.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   tenure            7043 non-null   int64
 2   Contract          7043 non-null   str
 3   PaperlessBilling  7043 non-null   str
 4   PaymentMethod     7043 non-null   str
 5   MonthlyCharges    7043 non-null   float64
 6   TotalCharges      7043 non-null   str
 7   Churn             7043 non-null   str
dtypes: float64(1), int64(1), str(6)
memory usage: 440.3 KB

## Transformação de dados

In [16]:
### Identificamos que a coluna TotalCharges está com um tipo diferente do que deveria ser, portanto, precisamos converter o tipo do dado para o correto.
### Devemos, antes de mais nada, garantir que não exista espaços vazios entre os valores. Para isso, usaremos o método 'to_numeric' com o parâmetro errors='coerce'

df_contracts.TotalCharges = pd.to_numeric(df_contracts.TotalCharges, errors='coerce')

In [ ]:
### Quando verificamos agora se a conversão funcionou, notamos que o TotalCharges agora é uma coluna do tipo "float64".
### Após a conversão, a coluna TotalCharges, passou a ter 11 valores ausentes.
df_contracts.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   tenure            7043 non-null   int64
 2   Contract          7043 non-null   str
 3   PaperlessBilling  7043 non-null   str
 4   PaymentMethod     7043 non-null   str
 5   MonthlyCharges    7043 non-null   float64
 6   TotalCharges      7032 non-null   float64
 7   Churn             7043 non-null   str
dtypes: float64(2), int64(1), str(5)
memory usage: 440.3 KB

## Como renomear colunas em um DF

In [ ]:
#Em casos de precisar mudar uma unica coluna específica, podemos usar a expressão abaixo
df_customers.rename(columns={'SeniorCitizen': 'Above65yo'}, inplace=True)

In [19]:
df_customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   customerID  7043 non-null   str
 1   gender      7043 non-null   str
 2   Above65yo   7043 non-null   int64
 3   Partner     7043 non-null   str
 4   Dependents  7043 non-null   str
dtypes: int64(1), str(4)
memory usage: 275.2 KB

In [ ]:
#Como queremos mudar todos os nomes de uma vez, podemos fazer isso da seguinte forma:
df_customers.columns = ['IDCliente', 'Genero', 'Mais65anos', 'TemParceiro', 'TemDependentes']

In [21]:
df_customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   IDCliente       7043 non-null   str
 1   Genero          7043 non-null   str
 2   Mais65anos      7043 non-null   int64
 3   TemParceiro     7043 non-null   str
 4   TemDependentes  7043 non-null   str
dtypes: int64(1), str(4)
memory usage: 275.2 KB

## Juntando todos os DF em um único (unificação de dataframes)

In [ ]:
#Primeiramente, precisamos contar a quantidade de registros por dataframes
len(df_services)

7043

In [23]:
len(df_contracts)

7043

In [24]:
len(df_customers)

7043

In [ ]:
 # Verificamos que todos os DFs estão com a mesma quantidade de registros.

Um ponto importante a ser destacado, as 3 tabelas possuem uma coluna em comum "costumer_id". Essa coluna é uma chave que conecta as 3 colunas. É importante lembrar que essa coluna foi renomeada em uma das tabelas para "IDCliente", portanto, devemos deixar em todas as tabelas o mesmo nome.

In [ ]:
# Alterando o nome das colunas 'customerID' dos DF services e contracts.
df_services.rename(columns={'customerID': 'IDCliente'}, inplace=True)
df_contracts.rename(columns={'customerID': 'IDCliente'}, inplace=True)

In [ ]:
# Unificando os DF Costumers e Services, criando um terceiro DF, onde iremos unir os dois em um.
df_temp = df_customers.merge(df_services, on=['IDCliente'])

In [39]:
#Podemos observar que conseguimos unificar os DFs
df_temp.head()

,IDCliente,Genero,Mais65anos,TemParceiro,TemDependentes,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
0,7590-VHVEG,Female,0,Yes,No,No,No phone service,DSL,No,Yes,No,No,No,No
1,5575-GNVDE,Male,0,No,No,Yes,No,DSL,Yes,No,Yes,No,No,No
2,3668-QPYBK,Male,0,No,No,Yes,No,DSL,Yes,Yes,No,No,No,No
3,7795-CFOCW,Male,0,No,No,No,No phone service,DSL,Yes,No,Yes,Yes,No,No
4,9237-HQITU,Female,0,No,No,Yes,No,Fiber optic,No,No,No,No,No,No

In [ ]:
# Unificando os DF df_temp e df_services, criando um df_churn (df definitivo), contendo as informações agora das 3 tabelas.
df_churn = df_temp.merge(df_contracts, on=['IDCliente'])

In [41]:
df_churn.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   IDCliente         7043 non-null   str
 1   Genero            7043 non-null   str
 2   Mais65anos        7043 non-null   int64
 3   TemParceiro       7043 non-null   str
 4   TemDependentes    7043 non-null   str
 5   PhoneService      7043 non-null   str
 6   MultipleLines     7043 non-null   str
 7   InternetService   7043 non-null   str
 8   OnlineSecurity    7043 non-null   str
 9   OnlineBackup      7043 non-null   str
 10  DeviceProtection  7043 non-null   str
 11  TechSupport       7043 non-null   str
 12  StreamingTV       7043 non-null   str
 13  StreamingMovies   7043 non-null   str
 14  tenure            7043 non-null   int64
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   str
dtypes: float64(2), int64(2), str(17)
memory usage: 1.1 MB